[project]
authors = [{name = "Srinivas Gorur-Shandilya", email = "code@srinivas.gs"}]
dependencies = ["xxhash>=3.5.0,<4"]
description = "Useful tools in python"
name = "thagomizer"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
thagomizer = { path = ".", editable = true }


[tool.pixi.tasks]

[tool.pixi.dependencies]
python = ">=3.13.0,<3.14"
beartype = ">=0.19.0,<0.20"

[tool.pixi.feature.dev.dependencies]
ipykernel = ">=6.29.5,<7"


[tool.pixi.feature.test.dependencies]
pytest = ">=8.3.4,<9"

[tool.pixi.feature.test.tasks]
test = "pytest"


[tool.pixi.environments]
dev = {features = ["dev"], solve-group = "default"}
test = {features = ["test"], solve-group = "default"}

