name: Test Python Code

on:
  # Allow manual runs
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.py'


jobs:



  code-formatting-syntax-and-docstrings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Check code formatting using ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.3.1
          args: format --check

      - name: Check import order
        uses: chartboost/ruff-action@v1
        with:
          version: 0.3.1
          args: check --select I

      - name: Check docstrings using interrogate
        run: |
          pip install interrogate 
          if [ $(interrogate -c pyproject.toml -v . -f 100 | grep "FAILED" | wc -l) = 1 ]; then
             echo "necessary docstrings missing:"
             interrogate -vv . -f 100 
             exit 1
          fi




  test:
    name: Test using python/uv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest 


  

