name: Test Python Code

on:
  # Allow manual runs
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.py'


jobs:



  code-formatting-syntax-and-docstrings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Check code formatting using ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.3.1
          args: format --check

      - name: Check import order
        uses: chartboost/ruff-action@v1
        with:
          version: 0.3.1
          args: check --select I

      - name: Check docstrings using interrogate
        run: |
          pip install interrogate 
          if [ $(interrogate -c pyproject.toml -v . -f 100 | grep "FAILED" | wc -l) = 1 ]; then
             echo "necessary docstrings missing:"
             interrogate -vv . -f 100 
             exit 1
          fi


  functionality-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    needs: [code-formatting-syntax-and-docstrings]
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          manifest-path: pyproject.toml
          pixi-version: v0.39.0
      - run: pixi run test


  

