name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
     - '*'

jobs:
  pypi-publish:
    name: Build and upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install


      - name: Build package
        run: 
          uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1




