name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
     - '*'

jobs:
  pypi-publish:
    name: Build and upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pypa/setuptools
        run: 
          python -m pip install build


      - name: Build package
        run: 
          python3 -m build --sdist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1




